
    create table Cuenta (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        valor integer not null,
        primary key (id)
    )

    create table Empresa (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )
