package parser;

/* Generated By:JavaCC: Do not edit this line. SCANNERConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SCANNERConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Identificador = 1;
  /** RegularExpression Id. */
  int Asignacion = 2;
  /** RegularExpression Id. */
  int NUMERO = 3;
  /** RegularExpression Id. */
  int OperadorPrimario = 4;
  /** RegularExpression Id. */
  int OperadorSecundario = 5;
  /** RegularExpression Id. */
  int FinDeLinea = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Identificador>",
    "\"=\"",
    "<NUMERO>",
    "<OperadorPrimario>",
    "<OperadorSecundario>",
    "\";\"",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
